# Generated by Django 4.2.2 on 2023-07-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_birth', models.DateField(auto_now=True)),
                ('age', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('account_type', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
    ]
